version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  web-tier:
  backend-tier:

services:
  cassandra:
    image: 'cassandra:3'
    ports:
      - "9042:9042"
    networks:
      - backend-tier

  todos:
    environment:
      SPRING_DATA_CASSANDRA_CONTACT_POINTS: cassandra
      SPRING_DATA_CASSANDRA_LOCAL_DATACENTER: datacenter1
      SPRING_DATA_CASSANDRA_KEYSPACE_NAME: todos
    image: "todos-application:native"
    entrypoint: wait-for-it cassandra:9042 -- /cnb/process/web
    ports:
      - 8181:8181
    networks:
      - web-tier
      - backend-tier
    depends_on:
     - cassandra

  prometheus:
    image: "prom/prometheus"
    depends_on:
      - todos
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - backend-tier
    restart: always

  grafana:
    image: "grafana/grafana"
    user: "104"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - backend-tier
      - web-tier