name: ci-build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: install libhyperic-sigar
        run: sudo apt-get install libhyperic-sigar-java

      - name: fetch head
        uses: actions/checkout@v2

      - name: setup jdk
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 11
          server-id: github
          settings-path: ${{ github.workspace }}/.mvn/

      - name: cache .m2
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: maven deploy
        run: ./mvnw -B -U clean deploy -s $GITHUB_WORKSPACE/.mvn/settings.xml -Ddockerfile.username=ssimmie -Ddockerfile.password=${{secrets.serverpass}}
        env:
          GITHUB_TOKEN: ${{secrets.serverpass}}

      - uses: actions/upload-artifact@v2-preview
        with:
          name: todos-build-artifacts
          path: ${{ github.workspace }}/**/target/**
