name: daily-build

on:
  schedule:
    - cron: "0 6 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: fetch head
        uses: actions/checkout@v2

      - name: setup jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github
          settings-path: ${{ github.workspace }}/config/.m2/
          
      - name: cache .m2
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: maven build
        run: ./mvnw -B -U verify -s $GITHUB_WORKSPACE/config/.m2/settings.xml
        env:
          GITHUB_TOKEN: ${{secrets.serverpass}}
