name: pr-build

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: install libhyperic-sigar
        run: sudo apt-get install libhyperic-sigar-java

      - name: setup docker compose compatibility
        run: |
          # Create a wrapper script that translates docker-compose commands to docker compose
          sudo tee /usr/local/bin/docker-compose > /dev/null <<'EOF'
          #!/bin/bash
          exec docker compose "$@"
          EOF
          sudo chmod +x /usr/local/bin/docker-compose

      - name: fetch head
        uses: actions/checkout@v4

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          settings-path: ${{ github.workspace }}/.mvn/

      - name: cache .m2
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: maven build
        run: ./mvnw -B verify -s $GITHUB_WORKSPACE/.mvn/settings.xml
        env:
          GITHUB_TOKEN: ${{secrets.serverpass}}
          NVD_API_KEY: ${{secrets.NVD_API_KEY}}

      - uses: actions/upload-artifact@v4
        with:
          name: todos-build-artifacts
          path: ${{ github.workspace }}/**/target/**
