name: pr-build

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: fetch head
        uses: actions/checkout@v2

      - name: setup jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11
          settings-path: ${{ github.workspace }}/.mvn/

      - name: cache .m2
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: maven build
        run: ./mvnw -B -U verify -s $GITHUB_WORKSPACE/.mvn/settings.xml
        env:
          GITHUB_TOKEN: ${{secrets.serverpass}}

      - name: 'Sending SMS Notification'
        uses: twilio-labs/actions-sms@v1
        with:
          fromPhoneNumber: '+1(256)3054846'
          toPhoneNumber: '+447413428082'
          message: 'PR build completed'
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}

      - uses: actions/upload-artifact@v2-preview
        with:
          name: todos-build-artifacts
          path: ${{ github.workspace }}/**/target/**
